# Generated by Django 6.0.1 on 2026-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mass_unit', models.CharField(choices=[('lb', 'Pounds'), ('oz', 'Ounces'), ('kg', 'Kilograms'), ('g', 'Grams')], default='lb', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
