# Generated by Django 6.0.1 on 2026-02-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_from', to='rates.address')),
                ('address_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_to', to='rates.address')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.parcel')),
            ],
        ),
    ]
