# Generated by Django 6.0.1 on 2026-05-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx'), ('ups', 'UPS'), ('usps', 'USPS')], max_length=20)),
                ('service_level', models.CharField(choices=[('ground', 'Ground'), ('express', 'Express Saver'), ('overnight', 'Overnight')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.shipment')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
