# Generated by Django 6.0.1 on 2026-06-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['amount_charged']},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='amount',
        ),
        migrations.AddField(
            model_name='rate',
            name='amount_carrier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
