# Generated by Django 6.0.1 on 2026-06-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_alter_rate_options_remove_rate_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('label_url', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rates.rate')),
            ],
        ),
    ]
